name: Build & Push Docker Images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }} # Tự động lấy từ secret

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Nhóm Frontend (Next.js) ---
          - app: admin
            dockerfile: ./Dockerfile.web
          - app: portal
            dockerfile: ./Dockerfile.web

          # --- Nhóm Backend (NestJS) ---
          - app: auth-service
            dockerfile: ./Dockerfile.backend
          - app: gateway
            dockerfile: ./Dockerfile.backend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push ${{ matrix.app }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/${{ matrix.app }}:latest
            ${{ env.IMAGE_NAME }}/${{ matrix.app }}:${{ github.sha }}
          # Truyền tên App vào Dockerfile để nó biết đường dẫn mà prune/copy
          build-args: |
            APP_NAME=${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max